set(0, ...
    'DefaultFigureColor', [1,1,1], ...              % Figure properties
    'DefaultFigurePaperType', 'A4', ...
    'DefaultFigurePaperUnits', 'centimeters', ...
    'DefaultFigurePaperSize', [18,10], ...
    'DefaultFigurePaperPosition', [0,0,get(0,'DefaultFigurePaperSize')], ...
    'DefaultFigureColor', 'w', ...
    'DefaultFigureInvertHardcopy', 'off', ...                             
    'DefaultAxesLayer', 'top', ...                  % Axes properties
    'DefaultAxesTickDir', 'out', ...    
    'DefaultAxesNextPlot', 'add', ...
    'DefaultAxesUnits', 'normalized', ...
    'DefaultAxesColor', 'none', ...
    'DefaultAxesBox' ,'off',...
    'defaultAxesLinewidth', 0.8, ...
    'DefaultAxesVisible', 'on', ...
    'DefaultLineLineStyle', '-', ...                % Line properties
    'DefaultLineMarker', 'none', ...
    'DefaultLineMarkerSize', 4, ...
    'DefaultLineMarkerFacecolor', [.2, .2, .9], ... % Colors
    'DefaultLineMarkerEdgecolor', [0,0,0], ...
    'DefaultAxesXcolor', [0, 0, 0], ...         
    'DefaultAxesYcolor', [0, 0, 0], ...
    'DefaultAxesZcolor', [0, 0, 0], ...
    'DefaultLineColor', [0, 0, 0], ...
    'DefaultAxesFontSize', 8, ...                  % Fonts and text properties
    'DefaultTextFontSize', 8, ...
    'DefaultAxesFontName', 'Arial', ...                     
    'DefaultTextColor', [0, 0, 0], ...
    'DefaultTextFontName', 'Arial', ...
    'DefaultTextVerticalAlignment', 'bottom', ...
    'DefaultTextHorizontalAlignment', 'left');
