%% Figure defaults
set(0, 'DefaultFigureColor', [1,1,1], ...
'DefaultFigurePaperType', 'A4', ...
'DefaultFigurePaperUnits', 'centimeters', ...
'DefaultFigurePaperSize', [15,10], ...
'DefaultFigurePaperPosition', [0,0,get(0,'DefaultFigurePaperSize')], ...
'DefaultFigureColor', 'w', ...
'DefaultFigureInvertHardcopy', 'off', ...
'DefaultAxesColor', 'none', ...
'DefaultAxesFontSize', 11, ...
'DefaultAxesFontName', 'Arial', ...
'DefaultAxesLayer', 'top', ...
'DefaultAxesNextPlot', 'replace', ...
'DefaultAxesUnits', 'normalized', ...
'DefaultAxesXcolor', [0.1, 0.1, 0.1], ...
'DefaultAxesYcolor', [0.1, 0.1, 0.1], ...
'DefaultAxesZcolor', [0.1, 0.1, 0.1], ...
'defaultAxesLinewidth', 1, ...
'DefaultAxesVisible', 'on', ...
'DefaultLineColor', 'k', ...
'defaultAxesBox' ,'off',...
'DefaultLineLineStyle', '-', ...
'DefaultLineMarker', 'none', ...
'DefaultLineMarkerSize', 5, ...
'DefaultTextColor', [0, 0, 0], ...
'DefaultTextFontSize', 11, ...
'DefaultTextFontName', 'Arial', ...
'DefaultTextVerticalAlignment', 'middle', ...
'DefaultTextHorizontalAlignment', 'left');
